version: "3.9"

services:
  app:
    build: .
    container_name: rails-app
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 3307
      DATABASE_USER: MJ
      DATABASE_PASSWORD: MJ12
      DATABASE_NAME: ban_note_development
    ports:
      - "3000:3000"
      - "50051:50051"
    volumes:
      - .:/rails
    command: bash -c "tail -f /dev/null"
