version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - ban_note_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ban_note_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - ban_note_network

  app:
    build: .
    depends_on:
      - redis
      - kafka
    ports:
      - "3000:3000"
      - "55005:55005"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: MJ
      DATABASE_PASSWORD: MJ12
      DATABASE_NAME: ban_note_development
      SECRET_KEY_BASE: aa91a6702241a3e22ed4b5f13353ab2ab9ff98949660dcb0a9b2e8150092ab2c6a4a766a2c820ab7bf0218d7deb894ccec222451a4f137532e43d501d2d24154
    volumes:
      - .:/rails
    command: bundle exec ruby grpc_service/server.rb
    networks:
      - ban_note_network

networks:
  ban_note_network:
    name: ban_note_shared_network
    external: true
